imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AgenceBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
  dbal:
    default_connection: default
    connections:

      default:
        server_version: "5.6"
        driver:   pdo_mysql
        host:     "127.0.0.1"
        port:     3306
        dbname:   agencies
        user:     root
        password: root
        charset:  UTF8

      tenant:
        server_version: "5.6"
        driver:   pdo_mysql
        host:     %database_host%
        port:     %database_port%
        dbname:   ~
        user:     ~
        password: ~
        wrapper_class: AppBundle\Connection\Wrapper  # Allows to specify a custom wrapper implementation to use.

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    default_entity_manager: default

    entity_managers:
      default:
        auto_mapping:     false # disabled so we can assign entities to our own connections
        connection:       default
        mappings:
            AppBundle:
              type:       yml
              mapping:    true
              dir:        %kernel.root_dir%/../src/AppBundle/Resources/config/doctrine/App
              prefix:     AppBundle\Entity
              is_bundle:  false

      tenant:
        auto_mapping:     false # disabled so we can assign entities to our own connections
        connection:       tenant
        mappings:
            AgenceBundle:
              type: yml
              mapping: true
              dir:        %kernel.root_dir%/../src/AgenceBundle/Resources/config/doctrine/Agency
              prefix:     AgenceBundle\Entity
              is_bundle:  false

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false
