AgenceBundle\Entity\Service:
    type: entity
    table: null
    repositoryClass: AgenceBundle\Repository\ServiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        icon:
            type: string
            length: 255
        description:
            type: string
            length: 255
    lifecycleCallbacks: {  }
